Refactor k1s to allow watching multiple resources

diff --git a/k1s b/k1s
--- a/k1s
+++ b/k1s
@@ -4,51 +4,65 @@
 for d in jq watch curl kubectl; do which "$d" >/dev/null || { echo "Missing dependency: $d"; exit 1; }; done
 ns=${1:-default}; res=${2:-pods}
 
-c() { echo -e "\033[$1m"; }
+resources=$(echo $res | sed 's/,/ /g')
+
+c()  { echo -e "\033[$1m"; }
 cc() { echo -e "\033[$1;1m"; }
 
 printf Loading && while true; do printf . && sleep 0.1; done &
-
-set -o pipefail
-path=$(kubectl get "$res" "$([[ "$ns" = - ]] && echo --all-namespaces || echo -n=$ns)" -v 6 2>&1 >/dev/null | grep GET | tail -n 1 | sed -n 's#.*https://[^/]*\([a-z0-9/.-]*\).*#\1#p')
-pid=$?
-kill -9 "$!" && wait "$!" 2>/dev/null
-[[ "$pid" -ne 0 ]] && echo -e "\nInvalid resource type: $res" && exit 1
-[[ $(echo -n "${path//[^\/]}" | wc -c) -lt 5 ]] && ns=-
-res=${path##*/}
+loading=$!
 
 exec 3< <(kubectl proxy -p 0)
 port=$(head -n 1 <&3 | sed 's/.*:\([0-9]\{4,5\}\).*/\1/')
 
-file=$(mktemp)
-cat <<EOF >"$file"
+file_header=$(mktemp); files="$file_header"
+cat <<EOF >"$file_header"
 $(cc 36) ____ ____ ____
 ||$(cc 33)k$(cc 36) |||$(cc 33)1$(cc 36) |||$(cc 33)s$(cc 36) ||  $(cc 0)Kubernetes Dashboard$(cc 36)
 ||__|||__|||__||  $(cc 0)Namespace: $ns$(cc 36)
-|/__\|/__\|/__\|  $(cc 0)Resources: $res$(c 0)
+|/__\|/__\|/__\|  $(cc 0)Resources: $resources$(c 0)
 
 EOF
 
-curl -N -s "http://localhost:$port$path?watch=true" |
-  while read -r event; do
-    name=$(jq -r '.object.metadata.name' <<<"$event")
-    case "$res" in
-    pods)
-      phase=$(jq -r '.object.status.phase' <<<"$event")
-      is_ready=$(jq -r 'if .object.status | has("conditions") then .object.status.conditions[] | if select(.type=="Ready").status=="True" then "1" else "" end else "" end' <<<"$event")
-      is_scheduled=$(jq -r 'if .object.status | has("conditions") then .object.status.conditions[] | if select(.type=="PodScheduled").status=="True" then "1" else "" end else "" end' <<<"$event")
-      [[ "$is_scheduled" && ! "$is_ready" ]] && info=NonReady || info=$phase
-      [[ "$info" = Running ]] && info=$(c 32)$info$(c 0) || info=$(c 33)$info$(c 0) ;;
-    deployments|replicasets|statefulsets)
-      spec=$(jq -r '.object.spec.replicas' <<<"$event")
-      stat=$(jq -r '.object.status.readyReplicas // 0' <<<"$event")
-      [[ "$stat" = "$spec" ]] && info="$(c 32)($stat/$spec)$(c 0)" || info="$(c 33)($stat/$spec)$(c 0)" ;;
-    esac
-    case $(jq -r .type <<<"$event") in
-      ADDED) echo "$name $info" >>"$file" ;;
-      MODIFIED) sed -i.bkp "s/^$name .*$/$name ${info//\//\\/}/" "$file" ;;
-      DELETED) sed -i.bkp "/^$name .*$/d" "$file";;
-    esac
-  done &
+set -o pipefail
 
-watch -ctn 0.1 cat "$file"
+watch_resource() {
+  local res=$1; shift
+  local file=$res_$(mktemp); files+=" $file"
+  echo > $file
+
+  path=$(kubectl get "$res" "$([[ "$ns" = - ]] && echo --all-namespaces || echo -n=$ns)" -v 6 2>&1 >/dev/null | grep GET | tail -n 1 | sed -n 's#.*https://[^
+/]*\([a-z0-9/.-]*\).*#\1#p')
+  pid=$?
+  kill -9 "$loading" && wait "$loading" 2>/dev/null
+  [[ "$pid" -ne 0 ]] && echo -e "\nInvalid resource type: $res" && exit 1
+  [[ $(echo -n "${path//[^\/]}" | wc -c) -lt 5 ]] && ns=-
+  res=${path##*/}
+
+  curl -N -s "http://localhost:$port$path?watch=true" |
+    while read -r event; do
+      name=$(jq -r '.object.metadata.name' <<<"$event")
+      case "$res" in
+      pods)
+        phase=$(jq -r '.object.status.phase' <<<"$event")
+        is_ready=$(jq -r 'if .object.status | has("conditions") then .object.status.conditions[] | if select(.type=="Ready").status=="True" then "1" else "" 
+end else "" end' <<<"$event")
+        is_scheduled=$(jq -r 'if .object.status | has("conditions") then .object.status.conditions[] | if select(.type=="PodScheduled").status=="True" then "
+1" else "" end else "" end' <<<"$event")
+        [[ "$is_scheduled" && ! "$is_ready" ]] && info=NonReady || info=$phase
+        [[ "$info" = Running ]] && info=$(c 32)$info$(c 0) || info=$(c 33)$info$(c 0) ;;
+      deployments|replicasets|statefulsets)
+        spec=$(jq -r '.object.spec.replicas' <<<"$event")
+        stat=$(jq -r '.object.status.readyReplicas // 0' <<<"$event")
+        [[ "$stat" = "$spec" ]] && info="$(c 32)($stat/$spec)$(c 0)" || info="$(c 33)($stat/$spec)$(c 0)" ;;
+      esac
+      case $(jq -r .type <<<"$event") in
+        ADDED) echo "$name $info" >>"$file" ;;
+        MODIFIED) sed -i.bkp "s/^$name .*$/$name ${info//\//\\/}/" "$file" ;;
+        DELETED) sed -i.bkp "/^$name .*$/d" "$file";;
+      esac
+    done &
+}
+
+for res in $resources; do watch_resource $res; done
+watch -ctn 0.1 cat "$files"
